# Nexys4 Pin Assignments
############################
# On-board clock source    #
############################
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_raw]

set_property PACKAGE_PIN E3 [get_ports clk_raw]
set_property IOSTANDARD LVCMOS33 [get_ports clk_raw]

############################
# On-board Push Switches   #
############################
#set_property PACKAGE_PIN T16 [get_ports in_open]
#set_property IOSTANDARD LVCMOS33 [get_ports in_open]
#set_property PACKAGE_PIN R10 [get_ports in_close]
#set_property IOSTANDARD LVCMOS33 [get_ports in_close]
#set_property PACKAGE_PIN F15 [get_ports out_up]
#set_property IOSTANDARD LVCMOS33 [get_ports out_up]
#set_property PACKAGE_PIN V10 [get_ports out_down]
#set_property IOSTANDARD LVCMOS33 [get_ports out_down]

############################
# On-board Slide Switches  #
############################
#set_property PACKAGE_PIN P4 [get_ports floor_choose[0]]
#set_property IOSTANDARD LVCMOS33 [get_ports floor_choose[0]]
#set_property PACKAGE_PIN P3 [get_ports floor_choose[1]]
#set_property IOSTANDARD LVCMOS33 [get_ports floor_choose[1]]
#set_property PACKAGE_PIN R3 [get_ports floor_choose[2]]
#set_property IOSTANDARD LVCMOS33 [get_ports floor_choose[2]]
#set_property PACKAGE_PIN T1 [get_ports floor_choose[3]]
#set_property IOSTANDARD LVCMOS33 [get_ports floor_choose[3]]
#set_property PACKAGE_PIN T3 [get_ports in_floor[1]]
#set_property IOSTANDARD LVCMOS33 [get_ports in_floor[1]]
#set_property PACKAGE_PIN U2 [get_ports in_floor[2]]
#set_property IOSTANDARD LVCMOS33 [get_ports in_floor[2]]
#set_property PACKAGE_PIN V2 [get_ports in_floor[3]]
#set_property IOSTANDARD LVCMOS33 [get_ports in_floor[3]]
set_property PACKAGE_PIN U4 [get_ports ram_choose[3]]
set_property IOSTANDARD LVCMOS33 [get_ports ram_choose[3]]
set_property PACKAGE_PIN V5 [get_ports ram_choose[2]]
set_property IOSTANDARD LVCMOS33 [get_ports ram_choose[2]]
set_property PACKAGE_PIN V6 [get_ports ram_choose[1]]
set_property IOSTANDARD LVCMOS33 [get_ports ram_choose[1]]
set_property PACKAGE_PIN V7 [get_ports ram_choose[0]]
set_property IOSTANDARD LVCMOS33 [get_ports ram_choose[0]]
set_property PACKAGE_PIN R5 [get_ports choose[4]]
set_property IOSTANDARD LVCMOS33 [get_ports choose[4]]
set_property PACKAGE_PIN R6 [get_ports choose[3]]
set_property IOSTANDARD LVCMOS33 [get_ports choose[3]]
set_property PACKAGE_PIN R7 [get_ports choose[2]]
set_property IOSTANDARD LVCMOS33 [get_ports choose[2]]
set_property PACKAGE_PIN U8 [get_ports choose[1]]
set_property IOSTANDARD LVCMOS33 [get_ports choose[1]]
set_property PACKAGE_PIN U9 [get_ports choose[0]]
set_property IOSTANDARD LVCMOS33 [get_ports choose[0]]

############################
# On-board led             #
############################
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets run_led]
#set_property PACKAGE_PIN T8 [get_ports run_led]
#set_property IOSTANDARD LVCMOS33 [get_ports run_led]
#set_property PACKAGE_PIN V9 [get_ports down_led]
#set_property IOSTANDARD LVCMOS33 [get_ports down_led]
#set_property PACKAGE_PIN R8 [get_ports up_led]
#set_property IOSTANDARD LVCMOS33 [get_ports up_led]
#set_property PACKAGE_PIN T6 [get_ports close_led]
#set_property IOSTANDARD LVCMOS33 [get_ports close_led]
#set_property PACKAGE_PIN T5 [get_ports open_led]
#set_property IOSTANDARD LVCMOS33 [get_ports open_led]
#set_property PACKAGE_PIN P2 [get_ports in_floor_led[1]]
#set_property IOSTANDARD LVCMOS33 [get_ports in_floor_led[1]]
#set_property PACKAGE_PIN R2 [get_ports in_floor_led[2]]
#set_property IOSTANDARD LVCMOS33 [get_ports in_floor_led[2]]
#set_property PACKAGE_PIN U1 [get_ports in_floor_led[3]]
#set_property IOSTANDARD LVCMOS33 [get_ports in_floor_led[3]]
#set_property PACKAGE_PIN P5 [get_ports in_floor_led[4]]
#set_property IOSTANDARD LVCMOS33 [get_ports in_floor_led[4]]
#set_property PACKAGE_PIN R1 [get_ports in_floor_led[5]]
#set_property IOSTANDARD LVCMOS33 [get_ports in_floor_led[5]]
#set_property PACKAGE_PIN V1 [get_ports in_floor_led[6]]
#set_property IOSTANDARD LVCMOS33 [get_ports in_floor_led[6]]
#set_property PACKAGE_PIN U3 [get_ports in_floor_led[7]]
#set_property IOSTANDARD LVCMOS33 [get_ports in_floor_led[7]]
#set_property PACKAGE_PIN V4 [get_ports in_floor_led[8]]
#set_property IOSTANDARD LVCMOS33 [get_ports in_floor_led[8]]

############################
# On-board 7_seg display   #
############################
set_property PACKAGE_PIN M1 [get_ports light_choose[7]]
set_property IOSTANDARD LVCMOS33 [get_ports light_choose[7]]
set_property PACKAGE_PIN L1 [get_ports light_choose[6]]
set_property IOSTANDARD LVCMOS33 [get_ports light_choose[6]]
set_property PACKAGE_PIN N4 [get_ports light_choose[5]]
set_property IOSTANDARD LVCMOS33 [get_ports light_choose[5]]
set_property PACKAGE_PIN N2 [get_ports light_choose[4]]
set_property IOSTANDARD LVCMOS33 [get_ports light_choose[4]]
set_property PACKAGE_PIN N5 [get_ports light_choose[3]]
set_property IOSTANDARD LVCMOS33 [get_ports light_choose[3]]
set_property PACKAGE_PIN M3 [get_ports light_choose[2]]
set_property IOSTANDARD LVCMOS33 [get_ports light_choose[2]]
set_property PACKAGE_PIN M6 [get_ports light_choose[1]]
set_property IOSTANDARD LVCMOS33 [get_ports light_choose[1]]
set_property PACKAGE_PIN N6 [get_ports light_choose[0]]
set_property IOSTANDARD LVCMOS33 [get_ports light_choose[0]]
set_property PACKAGE_PIN L3 [get_ports seg[0]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[0]]
set_property PACKAGE_PIN N1 [get_ports seg[1]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[1]]
set_property PACKAGE_PIN L5 [get_ports seg[2]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[2]]
set_property PACKAGE_PIN L4 [get_ports seg[3]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[3]]
set_property PACKAGE_PIN K3 [get_ports seg[4]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[4]]
set_property PACKAGE_PIN M2 [get_ports seg[5]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[5]]
set_property PACKAGE_PIN L6 [get_ports seg[6]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[6]]
set_property PACKAGE_PIN M4 [get_ports seg[7]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[7]]