# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/pc/Desktop/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/pc/Desktop/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/imports/ubuntu(1.1display)/number_to_7seg.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/imports/ubuntu(1.1display)/reg_neg.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/imports/ubuntu(1.1display)/reg_pos.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/counter.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/imports/ubuntu(1.1display)/seven_seg_display.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/imports/ubuntu(1.1display)/MEM_WB.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/imports/ubuntu(1.1display)/control_unit.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/imports/ubuntu(1.1display)/RAM.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/imports/ubuntu(1.1display)/hazard_unit.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/imports/ubuntu(1.1display)/ROM.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/imports/ubuntu(1.1display)/EX_MEM.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/imports/ubuntu(1.1display)/ID_EX.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/imports/ubuntu(1.1display)/ALU.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/imports/ubuntu(1.1display)/regfile.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/imports/ubuntu(1.1display)/IF_ID.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/clkcontrol.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/imports/ubuntu(1.1display)/pipeline_mips_cpu.v
}
read_xdc C:/Users/pc/Desktop/project_1/project_1.srcs/constrs_1/new/cpu.xdc
set_property used_in_implementation false [get_files C:/Users/pc/Desktop/project_1/project_1.srcs/constrs_1/new/cpu.xdc]

synth_design -top pipeline_mips_cpu -part xc7a100tcsg324-1
write_checkpoint -noxdef pipeline_mips_cpu.dcp
catch { report_utilization -file pipeline_mips_cpu_utilization_synth.rpt -pb pipeline_mips_cpu_utilization_synth.pb }
